name: kas_warga
description: Aplikasi manajemen kas dan iuran RT/Komunitas.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true